spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:1999/postgres
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
openapi:
  service:
    title: chat-service
    version: 1.0.0
    url: http://localhost:1688

springdoc:
  api-docs:
    path: /chat-service/v3/api-docs
  swagger-ui:
    path: /chat-service/swagger-ui.html
