eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
server:
  port: 1688

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: category-service
          uri: lb://CATEGORY-SERVICE
          predicates: 
            - Path=/category-service/**
        - id: user-service
          uri: lb://USER-SERVICE
          predicates: 
            - Path=/api/v1/**   
