eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
server:
  port: 1688

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: category-service
          uri: lb://CATEGORY-SERVICE
          predicates: 
            - Path=/category-service/**
        - id: user-service
          uri: lb://USER-SERVICE
          predicates: 
            - Path=/api/v1/**
        - id: openapi
          uri: http://localhost:${server.port}
          predicates: 
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs
